.TH "helmeltrans" 1 1.0.4 "27 Nov 2021" "User Manual"

.SH NAME
helmeltrans

.SH DESCRIPTION
3D Ellipsoidal Coordinate Transformation Tool

With this tool transformation between ellipsoidal (B L H = LAT LON H) and cartesian (XYZ) coordinates can be managed.
The ellipsoid name, as well as both axes of the ellipsoid must be predefined in a seperate textfile (ellipsoid_infile).

.SH SYNOPSIS
helmeltrans [blh|xyz] src_infilename ellipsoid_infilename outfilename

.SH DIRECTION
.TP
xyz
convert B-L-H to X-Y-Z
.TP
blh
convert X-Y-Z to B-L-H

.SH FILES
.TP
ellipsoid data file format:

 name a b
.TP
blh data file format:

 B[1] L[1] H[1]
 ..   ..   ..
 ..   ..   ..
 B[n] L[n] H[n]
.TP
xyz data file format:

 X[1] Y[1] Z[1]
 ..   ..   ..
 ..   ..   ..
 X[n] Y[n] Z[n]

.SH EXAMPLE
 export EXAMP=/usr/share/doc/helmert3d/examples/
 export ELLIPS=/usr/share/doc/helmert3d/ellipsoids/

 helmeltrans xyz $EXAMP/testpoints_blh.txt $ELLIPS/GRS80.txt xyh.txt
 helmeltrans blh xyh.txt $ELLIPS/GRS80.txt blh.txt
 helmdiff3d examples/testpoints_blh.txt blh.txt

.SH COPYRIGHT
helmert3d:

Copyright (c) 2020 U. Niethammer

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

.SH SEE ALSO
 helmparms3d(1),
 helmert3d(1),
 helmdiff3d(1)

.SH CONTACT
 Website: https://github.com/dr-ni/helmert3d
