.TH "helmert3d" 1 1.0.3 "26 Nov 2021" "User Manual"

.SH NAME
helmert3d

.SH DESCRIPTION
3D Helmert transformation Tool

The 3D Helmert transformation (Xt=T+sRX) is a frequently used method in geodesy to produce transformations between different Cartesian coordinate systems.
.TP
where
 Xt = transformed coordinate vector
 X = initial coordinate vector
 T = translation vector
 R = rotation matrix including rx, ry, rz
 rx, ry, rz = rotations around the coordinate axes
 s = scale factor

.SH SYNOPSIS
helmert3d xyz_src_infilename param_infilename [xyz_outfilename]

.SH FILES
.TP
xyz data file format:

 X[1] Y[1] Z[1]
 ..   ..   ..
 ..   ..   ..
 X[n] Y[n] Z[n]
.TP
helmert parameter file format:

 r11 r12 r13
 r21 r22 r23
 r31 r32 r33
 tx ty tz
 s

.SH EXAMPLE
export EXAMP=/usr/share/doc/helmert3d/examples/

helmert3d $EXAMP/testpoints_src.txt testparms.txt

.SH COPYRIGHT
helmert3d:

Copyright (c) 2020 U. Niethammer

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

.SH SEE ALSO
 helmparms3d(1),
 helmdiff3d(1),
 helmblhtoxyz(1)

.SH CONTACT
 Website: https://github.com/dr-ni/helmert3d

