.TH "helmtmerc" 1 1.0.7 "22 Jul 2022" "User Manual"

.SH NAME
helmtmerc

.SH DESCRIPTION
Transverse Mercator Coordinate Transformation Tool

The transverse Mercator projection in its various forms is the most widely used projected coordinate system for world
topographical and offshore mapping. It is a conformal projection in which a chosen meridian projects to a straight
line at constant scale.

.SH SYNOPSIS
helmeltrans {blh|xyz} src_infilename ellipsoid_infilename [outfilename]

.SH DIRECTION
.TP
xyh
convert B-L-H to x-y-H
.TP
blh
convert x-y-H to B-L-H

.SH FILES
.TP
ellipsoid data file format:

 name a b
.TP
zone data file format:

 zone_size zone_number [zone_scale] [L0] [x0] [y0]
.TP
blh data file format:

 B[1] L[1] H[1]
 ..   ..   ..
 ..   ..   ..
 B[n] L[n] H[n]
.TP
xyh data file format:

 x[1] y[1] H[1]
 ..   ..   ..
 ..   ..   ..
 x[n] y[n] H[n]

.SH EXAMPLE
 export EXAMP=/usr/share/doc/helmert3d/examples/
 export ELLIPS=/usr/share/doc/helmert3d/ellipsoids/
 export ZONES=/usr/share/doc/helmert3d/zones/

 helmtmerc xyh $EXAMP/testpoints_blh.txt $ELLIPS/GRS80.txt $ZONES/6g4zone.txt xyh.txt
 helmtmerc blh xyh.txt $ELLIPS/GRS80.txt $ZONES/6g4zone.txt blh.txt
 helmdiff3d examples/testpoints_blh.txt blh.txt

.SH COPYRIGHT
helmtmerc:

Copyright (c) 2021 U. Niethammer

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful, but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.

.SH SEE ALSO
 helmparms3d(1),
 helmert3d(1),
 helmeltrans(1),
 helmdiff3d(1)

.SH CONTACT
 Website: https://github.com/dr-ni/helmert3d
